name: Run DamaDam Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */1 * * *"   # Every 6 hours instead of every 2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run scraper
      env:        # 👇 yahan secrets ko inject karo
        DD_USERNAME: ${{ secrets.DD_USERNAME }}
        DD_PASSWORD: ${{ secrets.DD_PASSWORD }}
        SHEET_URL: ${{ secrets.SHEET_URL }}
        SERVICE_JSON: ${{ secrets.SERVICE_JSON }}
      run: |
        python scraper.py
